// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lghkvvomrxrgatbtzuai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnaGt2dm9tcnhyZ2F0YnR6dWFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTgzMDIsImV4cCI6MjA1Nzg5NDMwMn0.3BMEK35WgQ9mYjTN9I9LjT60N1qxa3_jHQoffrnveco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);